workflow: Test Self hosted runner

on: push
  branches:
    - test-gh-runner
  
  jobs:
    test:
    runs-on:
      - test-runner-app
    steps:
      run: |
        echo "test on my GH self hosted runner"